---

- fail: msg="site_name, site_domain, site_web_root parameters are not defined"
  when: site_name is not defined or site_domain is not defined or site_web_root is not defined

- name: install package
  apt: name={{ item }}
  with_items:
    - nginx

- name: create nginx configuration file
  template:
    src=nginx.conf.j2
    dest=/etc/nginx/sites-available/{{ site_name }}
