---
# Create user and its home directory

- name: Creates webroot
  file: path={{ site_web_root }} state=directory

- name: create user {{ webapp_username }} with home {{ site_web_root }}
  user: name={{ webapp_username }} home={{ site_web_root }} move_home=yes shell=/bin/bash comment="Account webapp {{ site_domain }}"

- name: change permission on home
  file: path={{ site_web_root }} state=directory owner={{ webapp_username }} mode=755

- name: Creates webroot app
  file: path={{ site_web_root }}/{{ item }} state=directory owner={{ webapp_username }}
  with_items:
    - app
    - static
    - media

- name: create .ssh/
  file: path={{ site_web_root }}/.ssh/ state=directory owner={{ webapp_username }} mode=700

- name: create authorized_keys
  file: path={{ site_web_root }}/.ssh/authorized_keys state=touch owner={{ webapp_username }} mode=600