---
- name: generate private key
  command: >
    openssl req -new -newkey rsa:2048 -keyout {{ site }}.key -nodes -out {{ site }}.csr -subj "/C={{ item.country|default('') }}/ST={{ item.state|default('') }}/L={{ item.city|default('') }}/O={{ item.organization|default('') }}/OU={{ item.unit|default('') }}/CN={{ item.name }}/emailAddress={{ item.email|default('') }}" -days {{ item.days|default(3650) }}
    creates={{ site }}.key
  with_items: certs_parameters
  tags:
    - keys
