---
- name: check mandatory parameters
  fail: msg="db_user, db_name and db_password parameters are not defined"
  when: db_user is not defined or db_name is not defined or db_password is not defined
- name: install necessary packages
  apt: name={{ item }} state=present update_cache=yes cache_valid_time=3600
  with_items:
    - libpq-dev
    - python-psycopg2
    - postgresql-9.1

# we must explicitely call for restart since copy and replace don't trigger handlers
#- replace: dest=/etc/postgresql/9.1/main/postgresql.conf regexp="^#(listen_addresses\s+=\s+)'.+'" replace="\1'*'"
- copy: src=pg_hba.conf dest=/etc/postgresql/9.1/main/pg_hba.conf owner=postgres group=postgres mode=0644
- service: name=postgresql state=restarted

- name: create database
  postgresql_db:
    name="{{ db_name }}"
    login_user=postgres
    login_host=127.0.0.1

- name: create database user
  postgresql_user:
    db="{{ db_name }}"
    user="{{ db_user }}"
    password="{{ db_password }}"
    login_user=postgres
    login_host=127.0.0.1
# this task is executed only when the parameter "development" is passed
- name: give power for testing purpose
  postgresql_privs:
    db="{{ db_name }}"
    roles="{{ db_user }}"
    type=schema
    objs=public
    privs=CREATE
    login_user=postgres
    login_host=127.0.0.1
  when: development is defined