---
- name: check mandatory parameters
  fail: msg="db_user, db_name and db_password parameters are not defined"
  when: db_user is not defined or db_name is not defined or db_password is not defined

- name: install necessary packages
  apt: name={{ item }} state=present update_cache=yes cache_valid_time=3600
  with_items:
    - libpq-dev
    - python-psycopg2
    - postgresql-9.1

- name: create database
  su: yes
  su_user: postgres
  postgresql_db:
      name="{{ db_name }}"

# https://groups.google.com/forum/#!topic/ansible-project/IknBo5QvJXQ
- name: create database user {% if development is defined %}(development mode){% endif %}
  su: yes
  su_user: postgres
  postgresql_user:
      db="{{ db_name }}"
      user="{{ db_user }}"
      password="{{ db_password }}"
      role_attr_flags={% if development is not defined %}NO{% endif %}CREATEDB,NOSUPERUSER

- service: name=postgresql state=restarted